# Generated by Django 4.2.2 on 2023-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answer_text_alter_question_text_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
