# Generated by Django 4.2.2 on 2023-06-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='profile',
        ),
    ]
