# Generated by Django 4.2.2 on 2023-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_answer_rating_alter_question_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpeg', upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
